"""add created_at column to diary

Revision ID: c51c00983e06
Revises: ed7e50cfead6
Create Date: 2025-04-06 17:27:05.418531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51c00983e06'
down_revision: Union[str, None] = 'ed7e50cfead6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_depression_score_score_id', table_name='depression_score')
    op.drop_table('depression_score')
    op.drop_index('ix_diary_diary_id', table_name='diary')
    op.drop_table('diary')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_survey_done', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=1)
    op.create_table('diary',
    sa.Column('diary_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('diary', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diary_id')
    )
    op.create_index('ix_diary_diary_id', 'diary', ['diary_id'], unique=1)
    op.create_table('depression_score',
    sa.Column('score_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('diary_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.diary_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index('ix_depression_score_score_id', 'depression_score', ['score_id'], unique=1)
    # ### end Alembic commands ###
